<?php

namespace Kwam\KwamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KwamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KwamRepository extends EntityRepository
{
}
